### PR TITLE
Say all responses in one message, not multiple

### PR DESCRIPTION
**Pull request by karx1**
# Pull Request

## Description:

 

This keeps the bot less spammy and reduces the chance we have of getting ratelimited by Discord.
It adds all the responses we have to an array, then, when we send the message, joins the array into a newline-separated string.

## Related Issue:

Not related to an issue

### CODE REVIEW

**Comment by nhcarrigan** [comment]
This has been rebased - @karx1 would you mind double-checking?

**Review by nhcarrigan — APPROVED** [review]
LGTM~! 🥳

**Comment by nhcarrigan** [comment]
@all-contributors please add @karx1 for code

**Comment by karx1** [comment]
@nhcarrigan The rebase is perfect, thanks!

**Pull request merged**
